### ISSUE TITLE
Ação no CRUD

### ISSUE THREAD

**Issue by Alcala** [leomaurodesenv/SysCGenerator#1]
Boa tarde, achei seu projeto aqui no github e achei muito interessante, só que tive um probleminha e queria confirmar com você. Os botões do CRUD não funcionam. Não consigo editar, adicionar, excluir nada.

**Comment by leomaurodesenv** [comment]
Boa tarde, que ótimo que acho interessante o projeto! Obrigado pelo feedback.

Vamos lá. 
Possivelmente ele não consegui encontrar os arquivos do JavaScript ou está com Problemas de conexão de banco de dados. 
**1)** Você configurou o `config.ini` modificando os valores da variável para os dados do seu servidor (ele funciona em servidor local e online - indiferente)
**2)** Caso o problema persista tente verificar qual o *log* no Web Console do navegardor. 
    * No Google Chrome você aperta Ctrl+Shitf+J
    * No Firefox você aperta F12 ou Ctrl+Shift+k
Veja o que está escrito no Web Console, copie e mande neste issue.
**3)** Estou trabalhando numa nova versão, otimizei alguns processos e estou tornando o código mais limpo, caso queria receber notificações marque a Estrela e Watch no projeto. Também mande um printscreen se possível.
    
Qualquer coisa é só falar. Aguardo seu resultado!

**Comment by Alcala** [comment]
Fiquei muito interessado mesmo! Gostaria de fazer um sistema parecido, mas sou bem leigo no PHP.
1) O que seria o path_default? É o caminho para a pasta JS?

**Comment by Alcala** [comment]
![create](https://cloud.githubusercontent.com/assets/21344379/26034726/44946c16-3897-11e7-8b8b-82b9484528b5.jpg)
Quando tento executar qualquer ação, o console aponta isso como erro.

**Comment by leomaurodesenv** [comment]
Ele não está encontrando os arquivos. Isto acontece porque o caminho está errado. 
O `path_define`  define os caminhos dos arquivos do sistema da seguinte forma:

```txt
path_online -> Caminho online do seu sistema (url)
path_pages -> Páginas de CRUD
path_default -> Outras páginas de uso geral do sistema.
```

Logo, se você não modificou o sistema, apenas instalou, o `path_pages` e `path_default` não serão modificados.
Observando seu *screnshot* acredito que você deva configurar da seguinte forma:

```php
[path_define]
path_online = "http://127.0.0.1/sysgerador"
path_pages = "/pages"
path_default = "/default"
```

**Comment by Alcala** [comment]
Consegui funcionar! Obrigado Leonardo!
Sem querer abusar muito de você, eu conseguiria montar - a partir do seu - um sistema que cada participante tivesse um login/senha e aparecesse apenas os certificados dele?

**Comment by leomaurodesenv** [comment]
Que ótimo que deu certo!

Acredito que não, pois os certificados estão vinculados ao "criador" do evento e não aos usuários. O propósito de não precisar o usuário criar login/senha que torna prático, de forma que qualquer pessoa a qualquer momento pode resgatar seu certificado. Mas você me pergunta: Por que? Caso as pessoas precisem verificar a validade do seu certificado isso pode ser feito de forma rápida e simples. Além do mais, caso você perca seu certificado você pode facilmente recuperar.

Adotei sua sugestão da seguinte forma: Acredito que uma das melhorias seria pesquisar o certificado pelo nome ou CPF, de forma que listasse todos os certificados da respectiva pessoa.

Infelizmente estou atrelado com outras tarefas no momento, mas acredito que até final do mês que vem saia uma nova versão. Mais estruturada e robusta.

**Comment by Alcala** [comment]
Entendi! Então, levantei essa questão pelo fato de que o CPF de cada participante ficaria exposto a qualquer um no site. Por isso que falei do login/senha e de buscar somente os certificados de cada usuário.

Muito obrigado pelas respostas! No aguardo dessa nova versão!

**Comment by leomaurodesenv** [comment]
Heheh.. de forma alguma o CPF e o nome seriam expostos. Seria utilizado como mecanismo de busca e não apresentação em forma de lista, da seguinte maneira:
Digite seu CPF -> Pessoa informa seu CPF -> Apresenta todos os certificados daquela Pessoa.

Disponha!

**Comment by Alcala** [comment]
Se bem que seria uma ótima opção essa a sua.
Eu sou bem leigo no PHP e queria conseguir montar algo parecido com o teu sistema. Você por acaso recomenda alguma fonte de estudo para PHP?

**Comment by leomaurodesenv** [comment]
Gosto bastante dos livros da [Novatec](https://novatec.com.br/).. 
Mas o importante é seguir uma linha de estudos, do básico a manipulações mais avançadas.
Por exemplo: primeiro como funciona as variáveis, funções e classes; seguido por manipulação de numeros, string.. até banco de dados. Até aqui você já terá um conhecimento legal de programação em PHP.

Depois você pode seguir para tópicos mais avançados como criptografia e desempenho de código.
